### ISSUE TITLE
Bug Archer arrow

### ISSUE THREAD

**Issue by rom-bar** [rom-bar/timkeren#124]
![error archer](https://cloud.githubusercontent.com/assets/12019808/9371980/9635beee-4703-11e5-8758-8ecf3dfc73d0.png)

error when playing game. especially when arju doing attack.

**Comment by kevin-liem** [comment]
@Brensenzz ini bug muncul di archer stelah km commit grenade arrow kliatannya
kira2 apa yg km ubah? bisa di check lg ndak?
saya bantu cek juga

**Comment by kevin-liem** [comment]
Stat : Done
Problem : there is null function trigger in animation system
